import{a as w,i as c,S as p}from"./assets/vendor-5401a4b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();async function g(r,t,i,s){return(await w.get(r,{params:{key:"42558235-d544995829d65acb68be95adf",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:i,per_page:s}})).data}const h=document.querySelector(".img-list");function y(r){const t=r.map(({largeImageURL:i,webformatURL:s,tags:e,likes:o,views:a,comments:L,downloads:v})=>`<li class="image-item">
    <a href="${i}">
                <img class="image" src="${s}" alt="${e}"/>
                <div class="image-info">
                    <p class="info"><b>Likes</b> ${o}</p>
                    <p class="info"><b>Views</b> ${a}</p>
                    <p class="info"><b>Comments</b> ${L}</p>
                    <p class="info"><b>Downloads</b> ${v}</p>
                </div>
            </a>
    </li>`).join("");return h.insertAdjacentHTML("beforeend",t)}let n=1;const d=15;let f;const u=document.querySelector(".image-search-form"),l=document.querySelector(".load-item"),m=document.querySelector(".load-button"),b="https://pixabay.com/api/";function S(){let t=document.querySelector(".img-list").getBoundingClientRect();if(t.height>0){let i=t.height;window.scrollBy({top:i,behavior:"smooth"})}}u.addEventListener("submit",async r=>{if(r.preventDefault(),n=1,h.innerHTML=null,f=r.currentTarget.input.value.trim(),f===""){c.show({title:"Error",titleColor:"#ffffff",message:"Write keyword to search images",messageColor:"#ffffff",backgroundColor:"#EF4040",position:"topRight",close:!1});return}l.classList.add("loader");let t;try{t=await g(b,f,n,d),t.hits.length<d?m.classList.add("hide"):m.classList.remove("hide"),t.hits.length===0&&c.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#ffffff",backgroundColor:"#EF4040",position:"topRight"}),l.classList.remove("loader")}catch(s){l.classList.remove("loader"),c.error({title:s.name,titleColor:"#ffffff",message:s.message,messageColor:"#ffffff",backgroundColor:"#EF4040",position:"topRight"})}y(t.hits),new p(".image-item a",{animationSpeed:300,captionsData:"alt",captionDelay:1e3,overlayOpacity:.5}).refresh(),u.reset()});m.addEventListener("click",async()=>{n++,l.classList.add("loader");const r=await g(b,f,n,d);l.classList.remove("loader"),y(r.hits),S(),new p(".image-item a",{animationSpeed:300,captionsData:"alt",captionDelay:1e3,overlayOpacity:.5}).refresh(),n*d>r.totalHits&&(m.classList.add("hide"),c.show({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"blue",messageColor:"#ffffff",timeout:1e3,position:"bottomRight",maxWidth:420}))});
//# sourceMappingURL=commonHelpers.js.map
